### PR TITLE
55 & 57 Update user dashboard page and create login

### LINKED ISSUE #55: Update user dashboard page
Currently user dashboard page has a link to create a group, but needs a list of groups/events if the user is already part of a group.

1. User logs in
2. If user does not have any groups, user sees link to create a group
3. If user is part of a group, user sees a list of their groups with the ability to click on any individual group
4. User also sees their upcoming events

### PR DESCRIPTION
**Pull request by marice-romero**
### Attached Issue

This PR resolves #55 and #57 

## Change Summary
- Added a Login form component to the Account Creation page to login existing users
- Updated the headers for both signup and login to reflect the passport.js setup
- Created a user state variable that stores the current user's ID, name, and email upon signup and login (note: there are already state variables for name and email but I didn't want to mess with them for now)
- Rather than displaying AuthenticatedContent in the same `signup` route after authentication, I added a redirect using `navigate` to display AuthenticatedContent on the already existing `/account` route. 
- Updated the AuthenticatedContent page to now display both the EventsDashboardContainer and GroupsDashboardContainer components (if they exist) or a message saying the user doesn't have any events or groups. The Create Group link is now at the bottom.
- Added the EventsDashboardContainer component to handle fetching all the user's events. Currently this is set up so that it's fetching ALL events and then filtering just the user's events (if they are host or participant) on the frontend - really not ideal, but we can create either a separate endpoint or add query params to filter on the backend later.
- Added the EventsDashboard component to display the user's upcoming events. Each event is a link which currently only links to a generic page but eventually should lead to all the information about that event.
- Added the GroupsDashboardContainer component to handle fetching all the user's groups. 
- Added the GroupsDashboard component to display the user's groups. Each group is a link which currently links to a generic page.
- I kept getting a 304 error code so I added cache-control headers to both the Groups and Events fetch requests.
- Added a ViewSingleGroup and ViewSingleEvent components just to test whether the group and events links were working.
- Added routes in app.js to ViewSingleGroup and ViewSingleEvent.

## I Had Difficulty With

Most of the headaches were getting the auth setup to work correctly (I kept getting a 401 error). At first I tested it all by creating a test branch on the backend that sent back a jwt-token and then stored the token in local storage on the frontend. Once passport.js got updated, it was actually fairly simple to get the auth requests working.

I also had some trouble with 304 error codes on my GET requests for Groups and Events. After some googling I added cache-control headers and that fixed it, although I'm not sure what any of that means.

We don't currently have an endpoint or query params in place to pull just the events the current user is part of (if there is, my apologies), so it took me a bit to come up with a solution that filtered the events on the frontend. It's fine for the v2 milestone but will need to be fixed in the future.

Also had difficulty getting the groups and events to render after their respective state values were updated, but this was fixed by adding conditional rendering.

### CODE REVIEW

**Comment by anniethewebcoder** [comment]
Would you `git pull` from `dev `and then merge with this branch? Your branch is about one or two steps behind `dev`'s latest commit? And I'll take care of the styling your codes.

**Comment by marice-romero** [comment]
Yep, dev is now merged

**Comment by anniethewebcoder** [comment]
Looks good!

**Comment by anniethewebcoder** [comment]
Yikes! I accidentally closed it. Now it's reopen. My bad.

**Review by anniethewebcoder — APPROVED** [review]
Great job!

**Review by dargaCode — APPROVED** [review]
Awesome work again, thank you!

Let's merge now and then open a couple of tickets to revisit one or two things 🙏

**Pull request merged**
