### PR TITLE
Update datacontainer url

### LINKED ISSUE #19: Deploy to production
- Make the backend url an environment variable that reads from `.env.development.local`
- Deploy `main` branch as a [Static Site](https://dashboard.render.com/static/new) to Render or as a site on Netlify.
- Set an environment variable for the backend url within Render or Netlify

### PR DESCRIPTION
**Pull request by anniethewebcoder**
This PR resolves #19 Deploy to production. I've set the environment variable on the deployed production.

### CODE REVIEW

**Comment by anniethewebcoder** [comment]
This is what it looks like on Netlify. 

image

**Review by angelkbrown — APPROVED** [review]
Looks great, Annie! 💯 Make sure to let the frontend team know that they will need to create a local env file with this variable to run it locally after pulling this change. Thanks so much for taking care of this! 🎉

**Review by dargaCode — CHANGES_REQUESTED** [review]
Awesome thank you for catching this @anniethewebcoder!

I added a small commit so people who don't have `VITE_BACKEND_URL` in their `.env` will get a reminder to add it:

Screen Shot 2023-12-10 at 1 44 03 PM

LIke Angel said though please do update the team with these new requirements as soon as you merge this PR!

https://github.com/Code-the-Dream-School/ee-prac-team2-front/pull/45/commits/0f2ff46736e8989568683aee994e979f58a3ea53

**Review by dargaCode — APPROVED** [review]

**Comment by dargaCode** [comment]
Woops sorry, Intended to hit Approve that first time

**Pull request merged**
